Change dockerfile to java17
GRAFO-URJC/WebGE pull request #215
Opened 2021-11-29 11:44 UTC by antoniocao99

He cambiado la version del dockerfile a 17.
He probado en mi maquina y todo parece ir bien.
Voy a lanzar este pull request para comprobar si sale build con exito.

2021-11-29 13:56 UTC, antoniocao99 commented
Sin embargo, segun veo en los github actions, tiene 2 steps que utiliza el JDK 11.
¿Debería cambiarse a 17?

2021-12-13 12:20 UTC, jmcolmenar commented
Los cambios que has hecho no modifican la compilación del proyecto. Hay que poner Java 17 en los siguientes ficheros:
- https://github.com/GRAFO-URJC/WebGE/blob/master/.github/workflows/build.yml
- En el pom.xml meter este trozo al mismo nivel que author, descripcion, etc:

```xml
<properties>
    <java.version>17</java.version>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
</properties>
```

Este cambio podrá tener efectos laterales que hay que revisar. Ten en cuenta también los tests.

2021-12-15 11:21 UTC, antoniocao99 commented
Añadidos los cambios necesarios + cambios al travis.yml

2021-12-17 12:50 UTC, rmartinsanta requested changes

2021-12-17 12:50 UTC, rmartinsanta commented on pom.xml
> +		<version>2.5.6</version><!-- cambie la version aqui -->
No hace falta dejar comentarios con los cambios, github o git te hacen el diff

2021-12-17 12:51 UTC, rmartinsanta commented
Revisa un pequeño comentario y lo mergeamos cuando este!

2021-12-17 15:14 UTC, antoniocao99 commented
Comentario del pom eliminado.

Listo para merge!

2021-12-17 15:28 UTC, merged